project:
  type: website
  output-dir: docs

website:
  title: "Stats_Paradigm_Project1_Ziying"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

